### ISSUE TITLE
Could not get app started 

### ISSUE THREAD

**Issue by KravMaguy** [zuixjs/zuix-html-pwa#2]
I tried to follow the tutorial, but it looks nothing like your version. and Im not getting any of the news feeds.
![Screenshot 2019-03-14 03 10 20](https://user-images.githubusercontent.com/37171082/54341044-d2174800-4606-11e9-9647-c803c4a6d26c.png)
Also the side bar slider is not working, its only working in the offline version. How do I fix it?

**Comment by genemars** [comment]
do not use localhost (127.0.0.1) during development, otherwise everything will be cached by the service worker and you will have to delete the application cache for every change you make. Instead use the LAN address (eg. 192.168.1.100) and activate the debugger (F12 key shortcut) and disable network caching.
